"""add notifications

Revision ID: 9f79017a9a56
Revises: e7454ee5cf8f
Create Date: 2026-09-20 23:50:45.748064

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "9f79017a9a56"
down_revision: str | None = "e7454ee5cf8f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recipient_id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "PROJECT_ASSIGNED",
                "PROJECT_UNASSIGNED",
                "TIMESHEET_EDITED",
                "MONTH_VALIDATED",
                "MONTH_REOPENED",
                "PROJECT_UPDATE_POSTED",
                "PROJECT_STATUS_CHANGED",
                "PROJECT_ARCHIVED",
                "PROJECT_DELETED",
                "USER_ROLE_CHANGED",
                "USER_DEACTIVATED",
                "USER_ACTIVATED",
                "API_KEY_CREATED",
                "API_KEY_REVOKED",
                "UPDATE_MENTION",
                name="notification_kind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("day", sa.Date(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("count", sa.Integer(), server_default="1", nullable=False),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["recipient_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_notification_inbox",
        "notifications",
        ["recipient_id", "read_at", "at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_actor_id"), "notifications", ["actor_id"], unique=False
    )
    op.create_index(op.f("ix_notifications_at"), "notifications", ["at"], unique=False)
    op.create_index(
        op.f("ix_notifications_kind"), "notifications", ["kind"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_project_id"),
        "notifications",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_recipient_id"),
        "notifications",
        ["recipient_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notifications_recipient_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_project_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_kind"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_at"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_actor_id"), table_name="notifications")
    op.drop_index("ix_notification_inbox", table_name="notifications")
    op.drop_table("notifications")
    # ### end Alembic commands ###
