"""widen entry values to quarters

Revision ID: b4c7e1a9d820
Revises: eb6813285102
Create Date: 2026-09-25 14:22:41.108374

An entry was a half day or a whole one, and after a few days of real use that
grain turned out not to hold: somebody carrying half a dozen projects cannot
cut a day into halves and have it come out right. The quarter — two hours on
an eight-hour day — is what the grid now takes.

Only the check constraint moves. The column is already a float, and the four
values are exactly representable in binary, so nothing is rewritten and no
month drifts.

Written by hand rather than autogenerated: `alembic check` does not see check
constraints, so the CI would have gone on passing while the database kept
refusing every quarter the domain accepted.

Going back is a widening in reverse, and it can fail — rightly. A quarter
already declared would break the narrower constraint, and PostgreSQL refuses
to add it rather than quietly dropping the rows that offend it. Anybody
downgrading with quarters in the table has to decide what becomes of them
first; there is no answer this migration could choose on their behalf.
"""

from collections.abc import Sequence

from alembic import op

revision: str = "b4c7e1a9d820"
down_revision: str | None = "eb6813285102"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

CONSTRAINT = "ck_entry_value"
QUARTERS = "value IN (0.25, 0.5, 0.75, 1.0)"
HALVES = "value IN (0.5, 1.0)"


def upgrade() -> None:
    op.drop_constraint(CONSTRAINT, "entries", type_="check")
    op.create_check_constraint(CONSTRAINT, "entries", QUARTERS)


def downgrade() -> None:
    op.drop_constraint(CONSTRAINT, "entries", type_="check")
    op.create_check_constraint(CONSTRAINT, "entries", HALVES)
