"""service registry fields on projects

Revision ID: 4a4d10caab4c
Revises: ca27120f6d05
Create Date: 2026-09-19 13:04:11.631926

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "4a4d10caab4c"
down_revision: str | None = "ca27120f6d05"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_dependencies",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("depends_on_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["depends_on_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("project_id", "depends_on_id"),
    )
    op.create_table(
        "project_stack",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("technology", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("project_id", "technology"),
    )
    op.create_table(
        "project_tags",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("tag", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("project_id", "tag"),
    )
    op.add_column("projects", sa.Column("slug", sa.String(length=100), nullable=True))
    op.add_column(
        "projects",
        sa.Column("is_published", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column("projects", sa.Column("summary", sa.Text(), nullable=True))
    op.add_column(
        "projects",
        sa.Column(
            "criticality",
            sa.Enum(
                "CRITICAL",
                "STANDARD",
                "SECONDARY",
                name="criticality",
                native_enum=False,
                length=16,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "projects",
        sa.Column(
            "service_type",
            sa.Enum(
                "FRONTEND",
                "BACKEND",
                "API",
                "FULLSTACK",
                "WORKER",
                "TOOL",
                name="service_type",
                native_enum=False,
                length=16,
            ),
            nullable=True,
        ),
    )
    op.add_column("projects", sa.Column("hosting", sa.String(length=64), nullable=True))
    op.add_column(
        "projects",
        sa.Column(
            "has_microsoft_entra", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column("projects", sa.Column("team", sa.String(length=64), nullable=True))
    op.add_column(
        "projects", sa.Column("slack_channel", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "projects", sa.Column("production_link", sa.String(length=2048), nullable=True)
    )
    op.add_column(
        "projects", sa.Column("staging_link", sa.String(length=2048), nullable=True)
    )
    op.add_column(
        "projects", sa.Column("repository_link", sa.String(length=2048), nullable=True)
    )
    op.add_column(
        "projects",
        sa.Column("documentation_link", sa.String(length=2048), nullable=True),
    )
    op.add_column(
        "projects",
        sa.Column("project_management_link", sa.String(length=2048), nullable=True),
    )
    op.add_column(
        "projects", sa.Column("monitoring_link", sa.String(length=2048), nullable=True)
    )
    op.add_column(
        "projects", sa.Column("stats_page_link", sa.String(length=2048), nullable=True)
    )
    op.add_column(
        "projects", sa.Column("stats_api_link", sa.String(length=2048), nullable=True)
    )
    op.create_index(
        op.f("ix_projects_is_published"), "projects", ["is_published"], unique=False
    )
    # Named by hand: an anonymous constraint cannot be dropped on downgrade.
    op.create_unique_constraint("uq_projects_slug", "projects", ["slug"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_projects_slug", "projects", type_="unique")
    op.drop_index(op.f("ix_projects_is_published"), table_name="projects")
    op.drop_column("projects", "stats_api_link")
    op.drop_column("projects", "stats_page_link")
    op.drop_column("projects", "monitoring_link")
    op.drop_column("projects", "project_management_link")
    op.drop_column("projects", "documentation_link")
    op.drop_column("projects", "repository_link")
    op.drop_column("projects", "staging_link")
    op.drop_column("projects", "production_link")
    op.drop_column("projects", "slack_channel")
    op.drop_column("projects", "team")
    op.drop_column("projects", "has_microsoft_entra")
    op.drop_column("projects", "hosting")
    op.drop_column("projects", "service_type")
    op.drop_column("projects", "criticality")
    op.drop_column("projects", "summary")
    op.drop_column("projects", "is_published")
    op.drop_column("projects", "slug")
    op.drop_table("project_tags")
    op.drop_table("project_stack")
    op.drop_table("project_dependencies")
    # ### end Alembic commands ###
