"""add project attachments

A mission may now carry files: a screen capture of a bug, a mock-up, a PDF of
the scoping. The row holds what the file is called, who dropped it and where
its bytes sit; the bytes themselves live in the object store — S3 in
production, MinIO on a laptop — and never in this table.

`storage_key` is unique because it is drawn, never derived from the name: two
`capture.png` dropped the same morning must not land on one another, and a
constraint is a better guarantee of that than the code that draws it.

The cascade on `project_id` takes the rows when a mission goes. It cannot
take the objects, which no database knows about: the use case deletes them
first, on purpose.

Revision ID: 65fbd74cd1f0
Revises: 9f79017a9a56
Create Date: 2026-09-21 20:35:29.384636

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "65fbd74cd1f0"
down_revision: str | None = "9f79017a9a56"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_attachments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("uploaded_by", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=255), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["uploaded_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_index(
        op.f("ix_project_attachments_project_id"),
        "project_attachments",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_project_attachments_project_id"), table_name="project_attachments"
    )
    op.drop_table("project_attachments")
    # ### end Alembic commands ###
