"""add weekly presence

Revision ID: 24d3ca86101d
Revises: 65fbd74cd1f0
Create Date: 2026-09-23 02:08:38.094024

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "24d3ca86101d"
down_revision: str | None = "65fbd74cd1f0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "presence_monday",
            sa.Enum(
                "ON_SITE",
                "REMOTE",
                "AWAY",
                name="day_presence",
                native_enum=False,
                length=8,
            ),
            server_default="ON_SITE",
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "presence_tuesday",
            sa.Enum(
                "ON_SITE",
                "REMOTE",
                "AWAY",
                name="day_presence",
                native_enum=False,
                length=8,
            ),
            server_default="ON_SITE",
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "presence_wednesday",
            sa.Enum(
                "ON_SITE",
                "REMOTE",
                "AWAY",
                name="day_presence",
                native_enum=False,
                length=8,
            ),
            server_default="ON_SITE",
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "presence_thursday",
            sa.Enum(
                "ON_SITE",
                "REMOTE",
                "AWAY",
                name="day_presence",
                native_enum=False,
                length=8,
            ),
            server_default="ON_SITE",
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "presence_friday",
            sa.Enum(
                "ON_SITE",
                "REMOTE",
                "AWAY",
                name="day_presence",
                native_enum=False,
                length=8,
            ),
            server_default="ON_SITE",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "presence_friday")
    op.drop_column("users", "presence_thursday")
    op.drop_column("users", "presence_wednesday")
    op.drop_column("users", "presence_tuesday")
    op.drop_column("users", "presence_monday")
    # ### end Alembic commands ###
