"""add project assignees

Revision ID: 5c139f15370d
Revises: bca651d9805c
Create Date: 2026-09-17 12:41:42.969231

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "5c139f15370d"
down_revision: str | None = "bca651d9805c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_assignees",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("project_id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_assignees")
    # ### end Alembic commands ###
