"""add activities and hang entries on them

An activity is the trade a mission's days are booked under, and it carries the
estimate for that trade. Entries keep their `project_id` — every reading that
aggregates by mission goes on working untouched — and gain a nullable
`activity_id` beside it. Nothing already declared is rewritten: what predates
this migration stays where it is, unattributed, which is the truth of it.

Both unique constraints are rebuilt NULLS NOT DISTINCT. Left as it is,
Postgres treats every null as different from every other, and two entries on
the same day, the same person and the same mission would both be accepted as
soon as the activity is null — which it is for all off-project work and for
everything this migration leaves in place.

Downgrading drops the column, and with it whichever activity each day had been
attributed to. The activities themselves go too.

Revision ID: 78e77d639db8
Revises: c946dce19b2a
Create Date: 2026-09-24 23:50:14.537938

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "78e77d639db8"
down_revision: str | None = "c946dce19b2a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column(
            "nature",
            sa.Enum(
                "DEVELOPMENT",
                "DESIGN",
                "PROJECT_MANAGEMENT",
                "DELIVERY",
                name="work_nature",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("estimated_days", sa.Float(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_activities_is_active"), "activities", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_activities_nature"), "activities", ["nature"], unique=False
    )
    op.create_index(
        op.f("ix_activities_project_id"), "activities", ["project_id"], unique=False
    )
    op.add_column("entries", sa.Column("activity_id", sa.Integer(), nullable=True))
    op.drop_constraint("uq_entry_slot", "entries", type_="unique")
    op.create_unique_constraint(
        "uq_entry_slot",
        "entries",
        ["user_id", "project_id", "activity_id", "day"],
        postgresql_nulls_not_distinct=True,
    )
    op.create_index(
        op.f("ix_entries_activity_id"), "entries", ["activity_id"], unique=False
    )
    op.create_foreign_key(
        "entries_activity_id_fkey",
        "entries",
        "activities",
        ["activity_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.add_column(
        "user_missions", sa.Column("activity_id", sa.Integer(), nullable=True)
    )
    op.drop_constraint("uq_user_mission", "user_missions", type_="unique")
    op.create_unique_constraint(
        "uq_user_mission",
        "user_missions",
        ["user_id", "project_id", "activity_id", "month"],
        postgresql_nulls_not_distinct=True,
    )
    op.create_index(
        op.f("ix_user_missions_activity_id"),
        "user_missions",
        ["activity_id"],
        unique=False,
    )
    op.create_foreign_key(
        "user_missions_activity_id_fkey",
        "user_missions",
        "activities",
        ["activity_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "user_missions_activity_id_fkey", "user_missions", type_="foreignkey"
    )
    op.drop_index(op.f("ix_user_missions_activity_id"), table_name="user_missions")
    op.drop_constraint("uq_user_mission", "user_missions", type_="unique")
    op.create_unique_constraint(
        "uq_user_mission", "user_missions", ["user_id", "project_id", "month"]
    )
    op.drop_column("user_missions", "activity_id")
    op.drop_constraint("entries_activity_id_fkey", "entries", type_="foreignkey")
    op.drop_index(op.f("ix_entries_activity_id"), table_name="entries")
    op.drop_constraint("uq_entry_slot", "entries", type_="unique")
    op.create_unique_constraint(
        "uq_entry_slot", "entries", ["user_id", "project_id", "day"]
    )
    op.drop_column("entries", "activity_id")
    op.drop_index(op.f("ix_activities_project_id"), table_name="activities")
    op.drop_index(op.f("ix_activities_nature"), table_name="activities")
    op.drop_index(op.f("ix_activities_is_active"), table_name="activities")
    op.drop_table("activities")
    # ### end Alembic commands ###
