"""add project detail fields

Revision ID: 64c662bbc3ca
Revises: 5c139f15370d
Create Date: 2026-09-17 12:58:10.476997

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "64c662bbc3ca"
down_revision: str | None = "5c139f15370d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_departments",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column(
            "department",
            sa.Enum(
                "ADMINISTRATIF_FINANCIER",
                "BAILLEURS",
                "COPROPRIETE",
                "SERVICE_CLIENT",
                "OPERATIONS",
                "SYSTEME_INFORMATION",
                "RESSOURCES_HUMAINES",
                "MARKETING_COMMUNICATION_RSE",
                "TERTIAIRE",
                "AUTRE",
                name="department",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("project_id", "department"),
    )
    op.create_table(
        "project_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_project_links_project_id"),
        "project_links",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "project_phases_reached",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column(
            "statut",
            sa.Enum(
                "EXPLORATION",
                "CADRAGE",
                "REALISATION",
                "VALIDATION",
                "DEPLOIEMENT",
                "EXPLOITATION",
                name="project_status",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("reached_at", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("project_id", "statut"),
    )
    op.add_column(
        "project_assignees",
        sa.Column(
            "role",
            sa.Enum(
                "INTERVENANT",
                "REFERENT",
                name="project_role",
                native_enum=False,
                length=16,
            ),
            server_default="INTERVENANT",
            nullable=False,
        ),
    )
    # L'autogenerate ajoute la colonne mais laisse la cle primaire en l'etat :
    # sans ce remaniement, une personne ne pourrait pas etre a la fois
    # referente et intervenante d'une meme mission.
    op.drop_constraint("project_assignees_pkey", "project_assignees", type_="primary")
    op.create_primary_key(
        "project_assignees_pkey",
        "project_assignees",
        ["project_id", "user_id", "role"],
    )

    op.add_column("projects", sa.Column("contacts_metier", sa.Text(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "contacts_metier")
    op.drop_constraint("project_assignees_pkey", "project_assignees", type_="primary")
    op.create_primary_key(
        "project_assignees_pkey", "project_assignees", ["project_id", "user_id"]
    )
    op.drop_column("project_assignees", "role")
    op.drop_table("project_phases_reached")
    op.drop_index(op.f("ix_project_links_project_id"), table_name="project_links")
    op.drop_table("project_links")
    op.drop_table("project_departments")
    # ### end Alembic commands ###
