"""add last login to users

Revision ID: 35c002710125
Revises: d21f4c7bfb89
Create Date: 2026-09-17 21:43:31.913663

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "35c002710125"
down_revision: str | None = "d21f4c7bfb89"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("derniere_connexion", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "derniere_connexion")
    # ### end Alembic commands ###
