"""add board fields to projects

Revision ID: bca651d9805c
Revises: 7865847765f6
Create Date: 2026-09-17 01:46:13.763494

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "bca651d9805c"
down_revision: str | None = "7865847765f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "categorie",
            sa.Enum(
                "AUTOMATISER",
                "PERENNISER",
                "INNOVER",
                "STRUCTURER",
                name="project_category",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "projects", sa.Column("date_mise_en_service", sa.Date(), nullable=True)
    )
    op.add_column(
        "projects",
        sa.Column("position", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "position")
    op.drop_column("projects", "date_mise_en_service")
    op.drop_column("projects", "categorie")
    # ### end Alembic commands ###
