"""add project updates

Revision ID: d21f4c7bfb89
Revises: dbc93ff7d3ec
Create Date: 2026-09-17 14:05:38.846573

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "d21f4c7bfb89"
down_revision: str | None = "dbc93ff7d3ec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_updates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("texte", sa.Text(), nullable=False),
        sa.Column("publiee_le", sa.DateTime(), nullable=False),
        sa.Column("modifiee_le", sa.DateTime(), nullable=True),
        sa.Column("supprimee_le", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_project_updates_project_id"),
        "project_updates",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_project_updates_project_id"), table_name="project_updates")
    op.drop_table("project_updates")
    # ### end Alembic commands ###
