"""one trade per mission

A mission is cut into trades, and a trade is one thing: two « Développement »
on the same mission split its budget across two lines nobody can tell apart,
and leave whoever fills in a month choosing between two rows that say exactly
the same.

The index is partial on `is_active`: an archived activity no longer holds the
place, which is how a budget is started over without losing the days already
booked against the old line. NULLS NOT DISTINCT so that « no trade stated » is
itself unique — two of those would be as undecidable as two « Développement ».

Duplicates already in place are archived rather than deleted, keeping the one
that carries the most days and, at equal count, the oldest. Nothing is lost —
the days stay readable and the line can be brought back — and a deployment
does not fail on data somebody entered in good faith before the rule existed.
Downgrading drops the index; it cannot tell which activities it archived, so
they stay archived.

Revision ID: 649a063ff287
Revises: 78e77d639db8
Create Date: 2026-09-25 01:16:21.160710

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "649a063ff287"
down_revision: str | None = "78e77d639db8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Archive what the index would refuse, before it refuses it.
    op.execute(
        """
        UPDATE activities
        SET is_active = false, archived_at = now()
        WHERE id IN (
            SELECT id FROM (
                SELECT
                    a.id,
                    row_number() OVER (
                        PARTITION BY a.project_id, a.nature
                        ORDER BY
                            (SELECT count(*) FROM entries e
                             WHERE e.activity_id = a.id) DESC,
                            a.id ASC
                    ) AS rank
                FROM activities a
                WHERE a.is_active
            ) ranked
            WHERE rank > 1
        )
        """
    )

    op.create_index(
        "uq_activity_trade",
        "activities",
        ["project_id", "nature"],
        unique=True,
        postgresql_where=sa.text("is_active"),
        postgresql_nulls_not_distinct=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_activity_trade",
        table_name="activities",
        postgresql_where=sa.text("is_active"),
        postgresql_nulls_not_distinct=True,
    )
    # ### end Alembic commands ###
