"""add project description

Revision ID: dbc93ff7d3ec
Revises: 64c662bbc3ca
Create Date: 2026-09-17 13:56:41.780302

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "dbc93ff7d3ec"
down_revision: str | None = "64c662bbc3ca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("description", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "description")
    # ### end Alembic commands ###
