"""create timesheet core tables

Revision ID: 7865847765f6
Revises: 
Create Date: 2026-09-16 00:11:37.750199

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "7865847765f6"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "holidays",
        sa.Column("jour", sa.Date(), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("jour"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entra_oid", sa.String(length=64), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "TEAMMATE", "MANAGER", name="user_role", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("actif", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_actif"), "users", ["actif"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_entra_oid"), "users", ["entra_oid"], unique=True)
    op.create_table(
        "month_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("mois", sa.Date(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "OUVERT", "VALIDE", name="month_state", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("validated_at", sa.DateTime(), nullable=True),
        sa.Column("validated_by", sa.Integer(), nullable=True),
        sa.Column("reopened_at", sa.DateTime(), nullable=True),
        sa.Column("reopened_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["reopened_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["validated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "mois", name="uq_month_user"),
    )
    op.create_index(
        op.f("ix_month_status_mois"), "month_status", ["mois"], unique=False
    )
    op.create_index(
        op.f("ix_month_status_user_id"), "month_status", ["user_id"], unique=False
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "PROJET",
                "LOT",
                "HORS_PROJET",
                name="project_kind",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "statut",
            sa.Enum(
                "EXPLORATION",
                "CADRAGE",
                "REALISATION",
                "VALIDATION",
                "EXPLOITATION",
                name="project_status",
                native_enum=False,
                length=16,
            ),
            nullable=True,
        ),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("actif", sa.Boolean(), nullable=False),
        sa.Column("estime_j", sa.Float(), nullable=True),
        sa.Column("monday_item_id", sa.String(length=32), nullable=True),
        sa.Column("monday_subitem_id", sa.String(length=32), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["parent_id"], ["projects.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_actif"), "projects", ["actif"], unique=False)
    op.create_index(op.f("ix_projects_kind"), "projects", ["kind"], unique=False)
    op.create_index(
        op.f("ix_projects_parent_id"), "projects", ["parent_id"], unique=False
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "ENTRY_SET",
                "ENTRY_CLEAR",
                "MONTH_VALIDATE",
                "MONTH_REOPEN",
                "PROJECT_CREATE",
                "PROJECT_UPDATE",
                "PROJECT_STATUS_CHANGE",
                "USER_ROLE_CHANGE",
                "USER_DEACTIVATE",
                name="audit_action",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("target_user_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("jour", sa.Date(), nullable=True),
        sa.Column("old_value", sa.String(length=64), nullable=True),
        sa.Column("new_value", sa.String(length=64), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["target_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_log_action"), "audit_log", ["action"], unique=False)
    op.create_index(
        op.f("ix_audit_log_actor_id"), "audit_log", ["actor_id"], unique=False
    )
    op.create_index(op.f("ix_audit_log_at"), "audit_log", ["at"], unique=False)
    op.create_index(
        op.f("ix_audit_log_project_id"), "audit_log", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_log_target_user_id"),
        "audit_log",
        ["target_user_id"],
        unique=False,
    )
    op.create_table(
        "entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("jour", sa.Date(), nullable=False),
        sa.Column("valeur", sa.Float(), nullable=False),
        sa.Column(
            "statut_at_entry",
            sa.Enum(
                "EXPLORATION",
                "CADRAGE",
                "REALISATION",
                "VALIDATION",
                "EXPLOITATION",
                name="project_status",
                native_enum=False,
                length=16,
            ),
            nullable=True,
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint("valeur IN (0.5, 1.0)", name="ck_entry_valeur"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "project_id", "jour", name="uq_entry_slot"),
    )
    op.create_index(op.f("ix_entries_jour"), "entries", ["jour"], unique=False)
    op.create_index(
        op.f("ix_entries_project_id"), "entries", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_entries_user_id"), "entries", ["user_id"], unique=False)
    op.create_table(
        "user_missions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("mois", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "project_id", "mois", name="uq_user_mission"),
    )
    op.create_index(
        op.f("ix_user_missions_mois"), "user_missions", ["mois"], unique=False
    )
    op.create_index(
        op.f("ix_user_missions_project_id"),
        "user_missions",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_missions_user_id"), "user_missions", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_missions_user_id"), table_name="user_missions")
    op.drop_index(op.f("ix_user_missions_project_id"), table_name="user_missions")
    op.drop_index(op.f("ix_user_missions_mois"), table_name="user_missions")
    op.drop_table("user_missions")
    op.drop_index(op.f("ix_entries_user_id"), table_name="entries")
    op.drop_index(op.f("ix_entries_project_id"), table_name="entries")
    op.drop_index(op.f("ix_entries_jour"), table_name="entries")
    op.drop_table("entries")
    op.drop_index(op.f("ix_audit_log_target_user_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_project_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_at"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_actor_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_action"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_projects_parent_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_kind"), table_name="projects")
    op.drop_index(op.f("ix_projects_actif"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_month_status_user_id"), table_name="month_status")
    op.drop_index(op.f("ix_month_status_mois"), table_name="month_status")
    op.drop_table("month_status")
    op.drop_index(op.f("ix_users_entra_oid"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_actif"), table_name="users")
    op.drop_table("users")
    op.drop_table("holidays")
    # ### end Alembic commands ###
