"""add work rhythms

Revision ID: f618b895d2d2
Revises: 65fbd74cd1f0
Create Date: 2026-09-22 22:59:40.411522

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "f618b895d2d2"
down_revision: str | None = "65fbd74cd1f0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "work_rhythms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("monday", sa.Float(), nullable=False),
        sa.Column("tuesday", sa.Float(), nullable=False),
        sa.Column("wednesday", sa.Float(), nullable=False),
        sa.Column("thursday", sa.Float(), nullable=False),
        sa.Column("friday", sa.Float(), nullable=False),
        sa.Column(
            "declared_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "monday IN (0, 0.5, 1) AND tuesday IN (0, 0.5, 1) AND wednesday IN (0, 0.5, 1) AND thursday IN (0, 0.5, 1) AND friday IN (0, 0.5, 1)",
            name="ck_rhythm_values",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "effective_from", name="uq_rhythm_opening"),
    )
    op.create_index(
        op.f("ix_work_rhythms_effective_from"),
        "work_rhythms",
        ["effective_from"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_rhythms_user_id"), "work_rhythms", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_work_rhythms_user_id"), table_name="work_rhythms")
    op.drop_index(op.f("ix_work_rhythms_effective_from"), table_name="work_rhythms")
    op.drop_table("work_rhythms")
    # ### end Alembic commands ###
