"""add project milestones

Revision ID: 4505f7bc29f4
Revises: aef34c202357
Create Date: 2026-09-26 10:17:59.952135

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "4505f7bc29f4"
down_revision: str | None = "aef34c202357"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "milestones",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("expected_on", sa.Date(), nullable=False),
        sa.Column("reached_on", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_milestones_expected_on"), "milestones", ["expected_on"], unique=False
    )
    op.create_index(
        op.f("ix_milestones_project_id"), "milestones", ["project_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_milestones_project_id"), table_name="milestones")
    op.drop_index(op.f("ix_milestones_expected_on"), table_name="milestones")
    op.drop_table("milestones")
    # ### end Alembic commands ###
