"""api keys

Revision ID: 2582c8296b29
Revises: 4a4d10caab4c
Create Date: 2026-09-19 15:46:22.377590

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "2582c8296b29"
down_revision: str | None = "eea66569bd48"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("public_id", sa.String(length=12), nullable=False),
        sa.Column("secret_hash", sa.String(length=64), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("revoked_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["revoked_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_api_keys_owner_id"), "api_keys", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_api_keys_public_id"), "api_keys", ["public_id"], unique=True
    )
    op.create_table(
        "api_key_scopes",
        sa.Column("api_key_id", sa.Integer(), nullable=False),
        sa.Column(
            "scope",
            sa.Enum(
                "CATALOG_READ",
                "PROJECTS_READ",
                "PROJECTS_WRITE",
                "ENTRIES_READ",
                name="api_key_scope",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["api_key_id"], ["api_keys.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("api_key_id", "scope"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("api_key_scopes")
    op.drop_index(op.f("ix_api_keys_public_id"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_owner_id"), table_name="api_keys")
    op.drop_table("api_keys")
    # ### end Alembic commands ###
