"""add icon to project links

Revision ID: 4871820c1abc
Revises: 4e87ee3906b4
Create Date: 2026-09-17 23:34:40.896384

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "4871820c1abc"
down_revision: str | None = "4e87ee3906b4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_links",
        sa.Column(
            "icone",
            sa.Enum(
                "LIEN",
                "DEPOT",
                "MAQUETTE",
                "DOCUMENT",
                "TABLEUR",
                "PRESENTATION",
                "DOSSIER",
                "DISCUSSION",
                "TICKET",
                "VIDEO",
                name="link_icon",
                native_enum=False,
                length=32,
            ),
            server_default="LIEN",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_links", "icone")
    # ### end Alembic commands ###
